#!/bin/sh

info() {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

success() {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

printf "[ \033[00;33mSetup\033[0m ]\n"
info "Installing Homebrew"
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
success "Installing Homebrew"

info "Downloading dotfiles"
git clone https://github.com/jansedivy/dotfiles.git ~/.dotfiles --recursive
success "Downloading dotfiles"

cd ~/.dotfiles
scripts/bootstrap

exit 0
